swagger: "2.0"
info:
  description: Set Up the Flask Weather App that pulls climate data.
  version: "1.0.0"
  title: Surf Up
consumes:
  - application/json
produces:
  - application/json

basePath: /api/

# Paths supported by the server application
paths:
  /precipitation:
    get:
      operationId: app.precipitation
      tags:
        - Precipitation
      summary: Return the precipitation data for the last year.
      description: precipitation return an array with a pair of (Date, Float).
      responses:
        200:
          description: Successfully read precipitation data.
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: integer
                station:
                  type: "string"
                date:
                  type: "string"
                prcp:
                  type: number
                tobs:
                  type: number
